### ISSUE TITLE
Waypoints of Mission integration tests for default PX4 SITL Home are far away

### ISSUE THREAD

**Issue by shakthi-prashanth-m** [Dronecode/DronecodeSDK#247]
As discussed with @julianoes yesterday, while running Mission integration tests, I got below error:
```
WARN  [navigator] First waypoint too far away: 7094 meters, 900 max.
```
I'd set PX4 SITL Home to match First waypoint of Mission Survey as per @julianoes suggestion; I was able to run [MissionSurvey](https://github.com/dronecore/DroneCore/blob/develop/integration_tests/mission_survey.cpp#L50) test successfully.
But when I ran [MissionAddWaypointsAndFly](https://github.com/dronecore/DroneCore/blob/f0926830fd62b94d97609bf1bfbf31292acd2b2f/integration_tests/mission.cpp#L33), I got same error 

This is because the First waypoint choosen for these two tests are far away from their relative PX4 SITL Home.
So, I recommend we have to choose First waypoint within 900 meters from default PX4 SITL Home so that we can run all Mission integration tests without a need to configure PX4 SITL Home.

**Comment by julianoes** [comment]
We should move it to the default CI home position, thanks for the issue.
