### ISSUE TITLE
Implement backend for camera

### ISSUE THREAD

**Issue by julianoes** [Dronecode/DronecodeSDK#334]
- [x] TakePhoto
- [x] StartPhotoInterval
- [x] StopPhotoInterval
- [x] StartVideo
- [x] StopVideo
- [x] StartVideoStreaming
- [x] StopVideoStreaming
- [x] SetMode
- [x] SubscribeMode
- [x] SetVideoStreamSettings
- [x] SubscribeVideoStreamInfo
- [x] SubscribeCaptureInfo
- [x] SubscribeCameraStatus
- [x] SubscribeCurrentSettings
- [x] SubscribePossibleSettings
- [x] SetSetting

**Comment by JonasVautherin** [comment]
Currently working on the C++ lib to conform to the gRPC interface [here](https://github.com/dronecore/DroneCore-Proto/pull/20). More specifically, the camera plugin is made for polling the mode/settings, and we want our language bindings to stream them instead.
