### ISSUE TITLE
Rename DroneCore class to dronecode::SDKCore

### ISSUE THREAD

**Issue by hamishwillee** [Dronecode/DronecodeSDK#340]
As per https://github.com/dronecore/DroneCore/issues/275#issuecomment-375713530

**Comment by shakthi-prashanth-m** [comment]
We have namespace `dronecore`. So we don't have to say dronecore again in the class name isn't it? We can now rename namespace to `dronecode`. And may keep class as `dronecode::SDKCore` ?

**Comment by shakthi-prashanth-m** [comment]
Or even `dronecode::CoreSDK` ?

**Comment by julianoes** [comment]
I'd vote `dronecode::SDKCore`, that's inline with the repo name.

**Comment by julianoes** [comment]
Well, this has been done a while ago.
