### ISSUE TITLE
Create dronecode SDK website page

### ISSUE THREAD

**Issue by hamishwillee** [Dronecode/DronecodeSDK#365]
The existing dronecore.io page should be duplicated, to appear at dronecode.org/sdk. 
* [x] Create draft page
* [x] Publish page
* [x] Create links from platform page, and from menu
* [x] Fix up links in page when docs move
* [x] Update page if needed to reflect any changes in "focus".
* [x] Ensure that dronecore.io is redirected to dronecode.org/sdk
* [x] Fix up Gitbook and website headers to remove Dronecore in header and replace with SDK.
* [x] Fix up dronecode architecture image [here](https://dev.px4.io/en/concept/dronecode_architecture.html) (devguide). Also add in CSD.
* [x] Search/replace over all docs and websites for DroneCore.

**Comment by hamishwillee** [comment]
Draft page has been created here: https://www.dronecode.org/wp-admin/post.php?post=2853&action=edit

**Comment by julianoes** [comment]
@hamishwillee I think only the redirect is missing and then we can close this.

**Comment by julianoes** [comment]
Redirect is done, closing.
