### ISSUE TITLE
what is DroneCores's uuid with multiple vehicles?

### ISSUE THREAD

**Issue by Seunghwan17** [Dronecode/DronecodeSDK#411]
I don't understand UUID is  became AUTOPILOT_VERSION's uid.

To explain my situation I have five drones.
According to the example, when dronecore make a system that need UUID. 

like below
DroneCore dc;
//... 
//Use UUID named uuid to get the associated System
System &system = dc.system(uuid);

But in dronecore's UUID is declared AUTOPILOT_VERSION's uid. My five drones have same AUTOPILOT_VERSION's uid and have different system ID. So, my five drones collision each others. 
I have question, my AUTOPILOT_VERSION's uid are same is strange or dronecore's uuid is strange?

I would be grateful if you could help with this phenomenon.

**Comment by julianoes** [comment]
Thanks for the question. In my opinion, the issue here is that each drone simulated by SITL has the same UUID. UUID stands "Universally unique identifier", which means they should be unique 😄 .

One workaround for you would be to add something to the UUID in each of your instances, so that they differ from each other.

And note that you also need to set different system IDs for each of the drones.

**Comment by Seunghwan17** [comment]
Um.. in my case I don't use SITL.
My five drones in real case.  My five different drones have same UUID.....
Maybe it is idiot question do you have many drones?

**Comment by julianoes** [comment]
> Um.. in my case I don't use SITL.

Oh, sorry. I was just assuming that. Ok, so what PX4 version are you using on them?
And could the issue be that DroneCore is still using the field `uid` instead of `uid2` in http://mavlink.org/messages/common#AUTOPILOT_VERSION? You can check if the `uid2` field is actually different.
We are planning to move to `uid2` in the future.

>  Maybe it is idiot question do you have many drones?

Good question 😄 . So I have a couple of drones but I have not used DroneCore with multiple drones at the same time. We've implemented it in a way to potentially support more than one but there might be some work left to get it to work properly.

**Comment by Seunghwan17** [comment]
![vehicle22](https://user-images.githubusercontent.com/37061413/40549019-4f8d42fc-6071-11e8-97a0-d2ed50286d8b.png)
![vehicle77](https://user-images.githubusercontent.com/37061413/40549021-503e77fc-6071-11e8-941e-0e90b6cc4a06.png)

this is my two drones.
these two drones have same uid. It is my  wondering. The situation that two drones have same value is  normal?

below two pictures are my drones version

![vehicle77-ver](https://user-images.githubusercontent.com/37061413/40549106-9208b652-6071-11e8-9958-756574145a45.png)
![vehicle22-ver](https://user-images.githubusercontent.com/37061413/40549110-934ee00e-6071-11e8-9636-02733ded7cb2.png)

**Comment by Seunghwan17** [comment]
Any my drones have PixRacer. AUTOPILOT_VERSION's uid and uid2 are same. But, ver'UIDs are different.

**Comment by julianoes** [comment]
That's odd, the uid and uid2 should be taken from the STM32 UUID of the chip, so that shouldn't happen.

I suggest you create an issue in PX4/Firmware and add all the detail for the two Pixracers.

**Comment by Seunghwan17** [comment]
Thanks. I create an issue in PX4/Firmware.
What isUUID's role in dronecore? It is important?
If is not, I try to replace UUID to system ID.

**Comment by julianoes** [comment]
yer, system ID should work too. Thea idea was to use UUID to be able to refer to individual vehicles over time and not just per session but that's currently not used yet anyway.

**Comment by mzahana** [comment]
@Seunghwan17 Did you manage to use Dronecode SDK with multiple drones?

I am trying to do the same, and I actually would like to use system ID (MAVLink ID which can be set by QGC), but I don't even see it available in the [System class](https://sdk.dronecode.org/en/api_reference/classdronecode__sdk_1_1_system.html)

@julianoes Is the MAVLink ID provided some how by the SDK?

Thanks.

**Comment by julianoes** [comment]
> @julianoes Is the MAVLink ID provided some how by the SDK?

No, only the UUID for now. Let's close this because the PX4 Firmware issue has been fixed and follow up in #486.

**Comment by Seunghwan17** [comment]
@mzahana oops.. I missed your message. In my case, I edit dronecode SDK to use sys ID not a UUID. As you see this post, UUID has some problem to me. If you want, I will show this code.

**Comment by julianoes** [comment]
Could you describe the problem that you are facing?

**Comment by mzahana** [comment]
I am working with a set of ordered drones. They have unique NAVLink IDs. So, it is easier for me to deal with system IDs than UUIDs.

**Comment by mzahana** [comment]
@Seunghwan17 I saw that system_id is available [here](https://github.com/Dronecode/DronecodeSDK/blob/develop/core/system_impl.cpp#L518)

The discussion is moved to https://github.com/Dronecode/DronecodeSDK/issues/486
