### ISSUE TITLE
v1.0.0 Changelog scratchpad

### ISSUE THREAD

**Issue by mrpollo** [Dronecode/DronecodeSDK#417]
Hey everyone I generated the following changelog, can we please review?

---

# Change Log

## [v1.0.0](https://github.com/dronecore/DroneCore/tree/v1.0.0) (2018-06-04)

[Full Changelog](https://github.com/dronecore/DroneCore/compare/v0.5.0...v1.0.0)

**Closed issues:**

- Add documentation for methods in device.h [\#296](https://github.com/dronecore/DroneCore/issues/296)

**Merged pull requests:**

- Public comments improvements [\#415](https://github.com/dronecore/DroneCore/pull/415) ([julianoes](https://github.com/julianoes))

## [v0.5.0](https://github.com/dronecore/DroneCore/tree/v0.5.0) (2018-06-04)

[Full Changelog](https://github.com/dronecore/DroneCore/compare/v0.4.0...v0.5.0)

**Implemented enhancements:**

- Python bindings for the core library [\#388](https://github.com/dronecore/DroneCore/issues/388)
- Examples should use consistent connection startup semantics [\#380](https://github.com/dronecore/DroneCore/issues/380)
- Implement mission features in backend [\#350](https://github.com/dronecore/DroneCore/issues/350)

**Fixed bugs:**

- transition\_vtol\_fixed\_wing example never ready to arm [\#401](https://github.com/dronecore/DroneCore/issues/401)
- fly\_qgc\_mission error loading shared libraries: libjson11.so [\#381](https://github.com/dronecore/DroneCore/issues/381)
- Mission subscribe blocked by mission pause [\#373](https://github.com/dronecore/DroneCore/issues/373)
- Random crash in Yuneec SDK [\#309](https://github.com/dronecore/DroneCore/issues/309)

**Closed issues:**

- fly\_mission and fly\_qgc\_mission examples freezes on mission accepted [\#399](https://github.com/dronecore/DroneCore/issues/399)
- \[Help\]  How to use DroneCore in HITL Gazebo [\#355](https://github.com/dronecore/DroneCore/issues/355)
- Implement remaining actions in backend [\#315](https://github.com/dronecore/DroneCore/issues/315)

**Merged pull requests:**

- Implement mission backend [\#416](https://github.com/dronecore/DroneCore/pull/416) ([JonasVautherin](https://github.com/JonasVautherin))
- camera: add set\_mode \(synchronous\) [\#414](https://github.com/dronecore/DroneCore/pull/414) ([JonasVautherin](https://github.com/JonasVautherin))
- core: fix macOS warning [\#413](https://github.com/dronecore/DroneCore/pull/413) ([julianoes](https://github.com/julianoes))
- Fix clang format [\#412](https://github.com/dronecore/DroneCore/pull/412) ([JonasVautherin](https://github.com/JonasVautherin))
- Switch to clang-format [\#410](https://github.com/dronecore/DroneCore/pull/410) ([julianoes](https://github.com/julianoes))
- Implement camera backend [\#409](https://github.com/dronecore/DroneCore/pull/409) ([JonasVautherin](https://github.com/JonasVautherin))
- backend: update proto and add camera [\#407](https://github.com/dronecore/DroneCore/pull/407) ([JonasVautherin](https://github.com/JonasVautherin))
- System refactor [\#406](https://github.com/dronecore/DroneCore/pull/406) ([julianoes](https://github.com/julianoes))
- Mission pause [\#405](https://github.com/dronecore/DroneCore/pull/405) ([Sushma7785](https://github.com/Sushma7785))
- Fix VTOL example [\#403](https://github.com/dronecore/DroneCore/pull/403) ([julianoes](https://github.com/julianoes))
- mission: fix warning about missing return [\#402](https://github.com/dronecore/DroneCore/pull/402) ([julianoes](https://github.com/julianoes))
- Make all examples use add\_any\_connection\(\) [\#400](https://github.com/dronecore/DroneCore/pull/400) ([hamishwillee](https://github.com/hamishwillee))
- Various fixes found doing camera tests [\#398](https://github.com/dronecore/DroneCore/pull/398) ([julianoes](https://github.com/julianoes))
- backend: add mission finished [\#397](https://github.com/dronecore/DroneCore/pull/397) ([JonasVautherin](https://github.com/JonasVautherin))
- Add thread pool [\#396](https://github.com/dronecore/DroneCore/pull/396) ([julianoes](https://github.com/julianoes))
- fly\_qgc\_mission: link to json11 [\#395](https://github.com/dronecore/DroneCore/pull/395) ([julianoes](https://github.com/julianoes))
- Fix connection comments [\#394](https://github.com/dronecore/DroneCore/pull/394) ([julianoes](https://github.com/julianoes))
- Fix timeout handler segfault [\#393](https://github.com/dronecore/DroneCore/pull/393) ([julianoes](https://github.com/julianoes))
- build\_system: remove build for armeabi [\#392](https://github.com/dronecore/DroneCore/pull/392) ([julianoes](https://github.com/julianoes))
- mavlink command fixes [\#391](https://github.com/dronecore/DroneCore/pull/391) ([julianoes](https://github.com/julianoes))
- core: use 251 as compid [\#390](https://github.com/dronecore/DroneCore/pull/390) ([julianoes](https://github.com/julianoes))
- Fix Mission lockup [\#387](https://github.com/dronecore/DroneCore/pull/387) ([julianoes](https://github.com/julianoes))
- build\_system: build tinyxml2 statically [\#386](https://github.com/dronecore/DroneCore/pull/386) ([JonasVautherin](https://github.com/JonasVautherin))
- mission: use latest commit of json11's fork [\#385](https://github.com/dronecore/DroneCore/pull/385) ([JonasVautherin](https://github.com/JonasVautherin))
- core: fix bad-cast on param\_get fail [\#384](https://github.com/dronecore/DroneCore/pull/384) ([julianoes](https://github.com/julianoes))
- core: fix conversion that now generates a warning [\#383](https://github.com/dronecore/DroneCore/pull/383) ([JonasVautherin](https://github.com/JonasVautherin))
- backend: fix wrong unit test in mission [\#382](https://github.com/dronecore/DroneCore/pull/382) ([JonasVautherin](https://github.com/JonasVautherin))
- backend: fix warning coming with new AppleClang [\#379](https://github.com/dronecore/DroneCore/pull/379) ([JonasVautherin](https://github.com/JonasVautherin))
- third\_party: use fork of json11 so that it builds as a static lib [\#378](https://github.com/dronecore/DroneCore/pull/378) ([JonasVautherin](https://github.com/JonasVautherin))
- Add action features [\#377](https://github.com/dronecore/DroneCore/pull/377) ([JonasVautherin](https://github.com/JonasVautherin))
- Finish telemetry features [\#376](https://github.com/dronecore/DroneCore/pull/376) ([JonasVautherin](https://github.com/JonasVautherin))
- Serial connection support for Windows [\#375](https://github.com/dronecore/DroneCore/pull/375) ([julianoes](https://github.com/julianoes))
- Add better support for note/warning types and update docs appopriately [\#374](https://github.com/dronecore/DroneCore/pull/374) ([hamishwillee](https://github.com/hamishwillee))
- Serial connection support for macOS [\#372](https://github.com/dronecore/DroneCore/pull/372) ([julianoes](https://github.com/julianoes))

## [v0.4.0](https://github.com/dronecore/DroneCore/tree/v0.4.0) (2018-04-26)

[Full Changelog](https://github.com/dronecore/DroneCore/compare/v0.3.0...v0.4.0)

**Implemented enhancements:**

- Rename "Mavlink" stuffs to that of "MAVLink" [\#329](https://github.com/dronecore/DroneCore/issues/329)
- Support for `COMMAND\_INT` [\#326](https://github.com/dronecore/DroneCore/issues/326)
- Return vectors by value in C++11 [\#319](https://github.com/dronecore/DroneCore/issues/319)
- Class name change: Device to System [\#318](https://github.com/dronecore/DroneCore/issues/318)
- Choosing reference over pointer [\#314](https://github.com/dronecore/DroneCore/issues/314)
- Add support to include Doxygen tags \code and \endcode [\#259](https://github.com/dronecore/DroneCore/issues/259)
- Rename `camera\_action\_delay\_s` to `loiter\_time\_s` in MissionItem class [\#249](https://github.com/dronecore/DroneCore/issues/249)
- Connection URL for DroneCore applications [\#244](https://github.com/dronecore/DroneCore/issues/244)
- FollowMeImpl::set\_config\(\) returns immediately though Device didn't confirm [\#221](https://github.com/dronecore/DroneCore/issues/221)
- Cross-compile the backend for iOS [\#213](https://github.com/dronecore/DroneCore/issues/213)
- Cross-compile the backend for Android [\#212](https://github.com/dronecore/DroneCore/issues/212)
- Have one gRPC server library for each plugin [\#211](https://github.com/dronecore/DroneCore/issues/211)
- Dynamically load plugins in dronecore\_server [\#210](https://github.com/dronecore/DroneCore/issues/210)
- device.h should become a library [\#209](https://github.com/dronecore/DroneCore/issues/209)
- Build core as a library [\#208](https://github.com/dronecore/DroneCore/issues/208)
- Build each plugin in its own library [\#207](https://github.com/dronecore/DroneCore/issues/207)
- Clarify FollowMe::Config::min\_height\_m and follow\_dist\_m  [\#204](https://github.com/dronecore/DroneCore/issues/204)
- Exposing Flight mode APIs in core/device\_impl.h [\#193](https://github.com/dronecore/DroneCore/issues/193)
- FollowMe API feels inconsistent [\#191](https://github.com/dronecore/DroneCore/issues/191)
- Follow Me has no example [\#189](https://github.com/dronecore/DroneCore/issues/189)
- Add public API to control camera outside of missions [\#154](https://github.com/dronecore/DroneCore/issues/154)
- Add Gimbal telemetry [\#141](https://github.com/dronecore/DroneCore/issues/141)
- Implement mavlink camera definition [\#126](https://github.com/dronecore/DroneCore/issues/126)
- Dynamic plug-in infrastructure [\#106](https://github.com/dronecore/DroneCore/issues/106)
- gRPC: APIs expose through gRPC [\#95](https://github.com/dronecore/DroneCore/issues/95)
- Improvements to core [\#359](https://github.com/dronecore/DroneCore/pull/359) ([shakthi-prashanth-m](https://github.com/shakthi-prashanth-m))
- Make use of smart pointers and references [\#316](https://github.com/dronecore/DroneCore/pull/316) ([shakthi-prashanth-m](https://github.com/shakthi-prashanth-m))
- Add Follow me example [\#217](https://github.com/dronecore/DroneCore/pull/217) ([shakthi-prashanth-m](https://github.com/shakthi-prashanth-m))

**Fixed bugs:**

- Mission items are not cleared before building them up [\#348](https://github.com/dronecore/DroneCore/issues/348)
- DroneCore application \(GCS\) should NOT mix up with System/Device [\#317](https://github.com/dronecore/DroneCore/issues/317)
- Takeoff example exits before vehicle is ready [\#307](https://github.com/dronecore/DroneCore/issues/307)
- Autoupilot type used for GCS is wrong [\#305](https://github.com/dronecore/DroneCore/issues/305)
- Script generate\_docs.sh doesn't identify whether build directory is empty [\#236](https://github.com/dronecore/DroneCore/issues/236)
- Running integration tests with `AUTOSTART\_SITL=1` fails [\#227](https://github.com/dronecore/DroneCore/issues/227)
- Device never gets connected again after heartbeat timed out [\#214](https://github.com/dronecore/DroneCore/issues/214)
- TCP connection drop causes high CPU usage [\#201](https://github.com/dronecore/DroneCore/issues/201)

**Closed issues:**

- Problems connecting to multiple PX4s in SITL [\#353](https://github.com/dronecore/DroneCore/issues/353)
- \[Mission\]Set speed function is not available [\#341](https://github.com/dronecore/DroneCore/issues/341)
- Implement telemetry health in backend [\#333](https://github.com/dronecore/DroneCore/issues/333)
- Implement frontend core [\#332](https://github.com/dronecore/DroneCore/issues/332)
- Maintain a connection instance per component in case of UDP [\#331](https://github.com/dronecore/DroneCore/issues/331)
- Run Takeoff Example Fail [\#301](https://github.com/dronecore/DroneCore/issues/301)
- Compile backend to a Framework on iOS [\#294](https://github.com/dronecore/DroneCore/issues/294)
- Camera plugin to implement MAVLink Camera Protocol client interface [\#292](https://github.com/dronecore/DroneCore/issues/292)
- Example for installing the DroneCore on Raspberrypi  [\#284](https://github.com/dronecore/DroneCore/issues/284)
- Missing sample plan for example [\#272](https://github.com/dronecore/DroneCore/issues/272)
- Update backend to new core proto [\#269](https://github.com/dronecore/DroneCore/issues/269)
- Update backend to new mission proto file [\#268](https://github.com/dronecore/DroneCore/issues/268)
- Update backend to new telemetry proto file [\#267](https://github.com/dronecore/DroneCore/issues/267)
- Can't build docs [\#245](https://github.com/dronecore/DroneCore/issues/245)
- Update dronecore\_server to use newly-defined action protocol [\#238](https://github.com/dronecore/DroneCore/issues/238)
- Flight testing DroneCore examples on Intel Aero [\#233](https://github.com/dronecore/DroneCore/issues/233)
- Unable to establish serial connection to PC [\#231](https://github.com/dronecore/DroneCore/issues/231)
- Error during make default [\#226](https://github.com/dronecore/DroneCore/issues/226)

**Merged pull requests:**

- Add telemetry features [\#371](https://github.com/dronecore/DroneCore/pull/371) ([JonasVautherin](https://github.com/JonasVautherin))
- build\_system: fix make clean [\#370](https://github.com/dronecore/DroneCore/pull/370) ([JonasVautherin](https://github.com/JonasVautherin))
- 350 mission backend [\#369](https://github.com/dronecore/DroneCore/pull/369) ([JonasVautherin](https://github.com/JonasVautherin))
- backend: add health to telemetry [\#362](https://github.com/dronecore/DroneCore/pull/362) ([JonasVautherin](https://github.com/JonasVautherin))
- Minor fixes to in-source docs following \#310 [\#361](https://github.com/dronecore/DroneCore/pull/361) ([hamishwillee](https://github.com/hamishwillee))
- core: notify already-connected systems on register\_on\_discover [\#360](https://github.com/dronecore/DroneCore/pull/360) ([JonasVautherin](https://github.com/JonasVautherin))
- backend: improve backend api and initialization [\#357](https://github.com/dronecore/DroneCore/pull/357) ([JonasVautherin](https://github.com/JonasVautherin))
- Added YCM conf file for vim YouCompleteMe [\#356](https://github.com/dronecore/DroneCore/pull/356) ([julianoes](https://github.com/julianoes))
- build\_system: remove unused-parameter flag for AppleClang [\#354](https://github.com/dronecore/DroneCore/pull/354) ([JonasVautherin](https://github.com/JonasVautherin))
- backend: add packaging scripts for iOS [\#352](https://github.com/dronecore/DroneCore/pull/352) ([JonasVautherin](https://github.com/JonasVautherin))
- Add support for COMMAND\_INT and abstraction for the same including `COMMAND\_LONG` [\#351](https://github.com/dronecore/DroneCore/pull/351) ([shakthi-prashanth-m](https://github.com/shakthi-prashanth-m))
- mission plugin: Clear old mission items [\#349](https://github.com/dronecore/DroneCore/pull/349) ([shakthi-prashanth-m](https://github.com/shakthi-prashanth-m))
- 269 update core proto [\#346](https://github.com/dronecore/DroneCore/pull/346) ([JonasVautherin](https://github.com/JonasVautherin))
- Add .ignore file to ignore everything third\_party [\#343](https://github.com/dronecore/DroneCore/pull/343) ([julianoes](https://github.com/julianoes))
- backend: update mission proto file [\#342](https://github.com/dronecore/DroneCore/pull/342) ([JonasVautherin](https://github.com/JonasVautherin))
- Added camera plugin with basic functionality [\#338](https://github.com/dronecore/DroneCore/pull/338) ([julianoes](https://github.com/julianoes))
- backend: fix protobuf to a specific git commit [\#330](https://github.com/dronecore/DroneCore/pull/330) ([JonasVautherin](https://github.com/JonasVautherin))
- action: move Action::Result out of action.h [\#328](https://github.com/dronecore/DroneCore/pull/328) ([JonasVautherin](https://github.com/JonasVautherin))
- 267 update telemetry proto [\#327](https://github.com/dronecore/DroneCore/pull/327) ([JonasVautherin](https://github.com/JonasVautherin))
- Function parameter reference/pointer types fix [\#324](https://github.com/dronecore/DroneCore/pull/324) ([hamishwillee](https://github.com/hamishwillee))
- Gimbal: add ROI command [\#323](https://github.com/dronecore/DroneCore/pull/323) ([bkueng](https://github.com/bkueng))
- fix backend following \#314 [\#320](https://github.com/dronecore/DroneCore/pull/320) ([JonasVautherin](https://github.com/JonasVautherin))
- backend: use parameterized tests in action\_service\_impl\_test [\#313](https://github.com/dronecore/DroneCore/pull/313) ([JonasVautherin](https://github.com/JonasVautherin))
- core: add HIL flag to SET\_MODE [\#312](https://github.com/dronecore/DroneCore/pull/312) ([julianoes](https://github.com/julianoes))
- device: fix reconnect [\#311](https://github.com/dronecore/DroneCore/pull/311) ([julianoes](https://github.com/julianoes))
- Multi component handling [\#310](https://github.com/dronecore/DroneCore/pull/310) ([shakthi-prashanth-m](https://github.com/shakthi-prashanth-m))
- Takeoff land example: Wait until vehicle is ready [\#308](https://github.com/dronecore/DroneCore/pull/308) ([shakthi-prashanth-m](https://github.com/shakthi-prashanth-m))
- Correct Autopilot type of Self \(GCS\) [\#306](https://github.com/dronecore/DroneCore/pull/306) ([shakthi-prashanth-m](https://github.com/shakthi-prashanth-m))
- backend: change backend dir [\#303](https://github.com/dronecore/DroneCore/pull/303) ([JonasVautherin](https://github.com/JonasVautherin))
- 238 update action proto [\#302](https://github.com/dronecore/DroneCore/pull/302) ([JonasVautherin](https://github.com/JonasVautherin))
- backend: clean pImpl [\#300](https://github.com/dronecore/DroneCore/pull/300) ([JonasVautherin](https://github.com/JonasVautherin))
- 294 ios backend framework [\#299](https://github.com/dronecore/DroneCore/pull/299) ([JonasVautherin](https://github.com/JonasVautherin))
- Enable markdown generation for global functions and enums [\#298](https://github.com/dronecore/DroneCore/pull/298) ([hamishwillee](https://github.com/hamishwillee))
- Add missing docs for ConnectionResult and connection\_result\_str [\#297](https://github.com/dronecore/DroneCore/pull/297) ([hamishwillee](https://github.com/hamishwillee))
- 238 refactor dronecore server [\#295](https://github.com/dronecore/DroneCore/pull/295) ([JonasVautherin](https://github.com/JonasVautherin))
- core: move ConnectionResult out of DroneCore class [\#290](https://github.com/dronecore/DroneCore/pull/290) ([JonasVautherin](https://github.com/JonasVautherin))
- Fix initializers for attribute prototypes [\#289](https://github.com/dronecore/DroneCore/pull/289) ([hamishwillee](https://github.com/hamishwillee))
- core: Move implementation into the pImpl. [\#288](https://github.com/dronecore/DroneCore/pull/288) ([JonasVautherin](https://github.com/JonasVautherin))
- mission: install libjson11.so for Android [\#287](https://github.com/dronecore/DroneCore/pull/287) ([julianoes](https://github.com/julianoes))
- build\_system: remove flags for unit tests in windows [\#283](https://github.com/dronecore/DroneCore/pull/283) ([JonasVautherin](https://github.com/JonasVautherin))
- telemetry: use absolute yaw for camera attitude [\#282](https://github.com/dronecore/DroneCore/pull/282) ([julianoes](https://github.com/julianoes))
- appveyor: try to run on more than one core [\#281](https://github.com/dronecore/DroneCore/pull/281) ([julianoes](https://github.com/julianoes))
- core: send HITL bit with DO\_SET\_MODE command [\#280](https://github.com/dronecore/DroneCore/pull/280) ([julianoes](https://github.com/julianoes))
- build\_system: build statically again for Mac [\#276](https://github.com/dronecore/DroneCore/pull/276) ([julianoes](https://github.com/julianoes))
- Appveyor: Add examples follow\_me and fly\_qgc\_mission [\#274](https://github.com/dronecore/DroneCore/pull/274) ([shakthi-prashanth-m](https://github.com/shakthi-prashanth-m))
- Update file path of QGC sample plan in the example [\#273](https://github.com/dronecore/DroneCore/pull/273) ([shakthi-prashanth-m](https://github.com/shakthi-prashanth-m))
- Update mission docs [\#271](https://github.com/dronecore/DroneCore/pull/271) ([hamishwillee](https://github.com/hamishwillee))
- style: add support for astyle 3.1 [\#270](https://github.com/dronecore/DroneCore/pull/270) ([JonasVautherin](https://github.com/JonasVautherin))
- Fix iOS \(non gRPC\) build [\#265](https://github.com/dronecore/DroneCore/pull/265) ([julianoes](https://github.com/julianoes))
- Add support for Connection URL arguments to Dronecore Applications [\#264](https://github.com/dronecore/DroneCore/pull/264) ([Rjasuja](https://github.com/Rjasuja))
- build\_system: create a static lib for Mac for now [\#263](https://github.com/dronecore/DroneCore/pull/263) ([julianoes](https://github.com/julianoes))
- Cross compile dronecore\_server for Android and iOS [\#261](https://github.com/dronecore/DroneCore/pull/261) ([JonasVautherin](https://github.com/JonasVautherin))
- \[WIP\] initial Jenkinsfile using docker [\#257](https://github.com/dronecore/DroneCore/pull/257) ([dagar](https://github.com/dagar))
- Fix linker error and lower Boost version in Follow Me example [\#256](https://github.com/dronecore/DroneCore/pull/256) ([shakthi-prashanth-m](https://github.com/shakthi-prashanth-m))
- Fix docker builds [\#255](https://github.com/dronecore/DroneCore/pull/255) ([julianoes](https://github.com/julianoes))
- cmake: add tinyxml2 install hack for Mac [\#253](https://github.com/dronecore/DroneCore/pull/253) ([julianoes](https://github.com/julianoes))
- cmake: install tinyxml2 library for Android [\#252](https://github.com/dronecore/DroneCore/pull/252) ([julianoes](https://github.com/julianoes))
- Makefile: fix make clean after make android [\#251](https://github.com/dronecore/DroneCore/pull/251) ([julianoes](https://github.com/julianoes))
- Fix offboard plugin creation in example [\#246](https://github.com/dronecore/DroneCore/pull/246) ([hamishwillee](https://github.com/hamishwillee))
- Fix up plugin constructor docs [\#242](https://github.com/dronecore/DroneCore/pull/242) ([hamishwillee](https://github.com/hamishwillee))
- build\_system: fix android build and make curl include more consistent [\#241](https://github.com/dronecore/DroneCore/pull/241) ([JonasVautherin](https://github.com/JonasVautherin))
- Enable external plugins again [\#239](https://github.com/dronecore/DroneCore/pull/239) ([julianoes](https://github.com/julianoes))
- Fix `generate\_doc.sh` issue \(\#236\) [\#237](https://github.com/dronecore/DroneCore/pull/237) ([shakthi-prashanth-m](https://github.com/shakthi-prashanth-m))
- Add QGC Mission import capability [\#235](https://github.com/dronecore/DroneCore/pull/235) ([shakthi-prashanth-m](https://github.com/shakthi-prashanth-m))
- Robustify mission upload/download [\#230](https://github.com/dronecore/DroneCore/pull/230) ([julianoes](https://github.com/julianoes))
- Fix issue: https://github.com/dronecore/DroneCore/issues/227 [\#228](https://github.com/dronecore/DroneCore/pull/228) ([shakthi-prashanth-m](https://github.com/shakthi-prashanth-m))
- mavlink: update submodule [\#225](https://github.com/dronecore/DroneCore/pull/225) ([julianoes](https://github.com/julianoes))
- Correct API description of Telemetry and Offboard plugins. [\#223](https://github.com/dronecore/DroneCore/pull/223) ([shakthi-prashanth-m](https://github.com/shakthi-prashanth-m))
- curl-android-ios: update for openssl headers [\#220](https://github.com/dronecore/DroneCore/pull/220) ([julianoes](https://github.com/julianoes))
- curl-android-ios: swap to dronecore fork [\#218](https://github.com/dronecore/DroneCore/pull/218) ([julianoes](https://github.com/julianoes))
- Keep previous uuid when Device disconnects [\#215](https://github.com/dronecore/DroneCore/pull/215) ([fklabach](https://github.com/fklabach))
- Set Flight Mode using new interface set\_flight\_mode in DeviceImpl [\#206](https://github.com/dronecore/DroneCore/pull/206) ([Rjasuja](https://github.com/Rjasuja))
- core: try to reconnect TCP connection [\#203](https://github.com/dronecore/DroneCore/pull/203) ([julianoes](https://github.com/julianoes))
- grpc: Support multiple device handling [\#202](https://github.com/dronecore/DroneCore/pull/202) ([Rjasuja](https://github.com/Rjasuja))
- Package integration test, generate .deb and .rpm [\#198](https://github.com/dronecore/DroneCore/pull/198) ([julianoes](https://github.com/julianoes))
- grpc: reorganize grpc [\#197](https://github.com/dronecore/DroneCore/pull/197) ([JonasVautherin](https://github.com/JonasVautherin))
- More flexible plugin architecture [\#188](https://github.com/dronecore/DroneCore/pull/188) ([julianoes](https://github.com/julianoes))

\* *This Change Log was automatically generated by [github_changelog_generator](https://github.com/skywinder/Github-Changelog-Generator)*

**Comment by julianoes** [comment]
@mrpollo that's nice to auto-generate it but I actually wrote the changelogs manually in the release notes, check out https://github.com/dronecore/DroneCore/releases. This way it's easier to read and less verbose.

**Comment by hamishwillee** [comment]
@julianoes The docs release happen after the fact, but should match your releases: https://github.com/dronecore/sdk_docs/releases
At the top is a link to associated docs. It might be worth creating just that link to the online version of the docs in the software release notes (?)

**Comment by anitha-suresh** [comment]
@mrpollo looks good! As it is auto generated, it would be effortless. I agree with Julian, that it looks too verbose. Can we please not categorize 'Fixed', 'Closed', 'Merged'. 

In release notes, it is easier and makes sense to mention at a higher level, about what feature or functionality is enabled (as there might be some 10 items/subtasks going as part of enabling one feature/function) AND also on the major bug fixes.

These are my thoughts :) Will wait for others to comment

**Comment by JonasVautherin** [comment]
> Can we please not categorize 'Fixed', 'Closed', 'Merged'.

There is a difference between those sections, but I believe the keywords are more: 'enhancements', 'bugs', 'issues', 'pull requests'. I guess the first two come from the labels. For the last two, the thing is that some PRs are not related to an issue.

If you want to simplify that, maybe we could just have 'bugs' and 'enhancements' (e.g. everything that is not labeled as a bug is an enhancement). And one question is whether we need to list both issues and PRs, or if we can keep only the PRs (because most of the time, issues are closed by PRs, but some PRs are not related to an issue). But then it means that we should make sure we put the 'bug' label on the PRs themselves.

@mrpollo I like the generated report! That is neat for the "full changes" report. And at the top we should probably highlight a few features/write a high-level description of the changes.

Gradle does it this way: they have some kind of blog post that says "now with gradle X.Y, you can do this, this, this and that!", then they have detailed explanations for those "key" features (sometimes linking to actual examples), and I believe they have a link to the full changelog somewhere.

**Comment by anitha-suresh** [comment]
Can we please not categorize 'Fixed', 'Closed', 'Merged' - I meant do we need all three as part of release notes.

**Comment by julianoes** [comment]
I'll continue doing this manually for now.
