### ISSUE TITLE
Dronecore as subproject

### ISSUE THREAD

**Issue by Stifael** [Dronecode/DronecodeSDK#424]
If dronecore is used as a subproject, in order to compile correctly with the correct paths, each plugin and core requires `target_include_directories(dronecore PUBLIC ${CMAKE_CURRENT_SOURCE_DIR})`, otherwise the header files will not be found.

**Comment by julianoes** [comment]
This has the drawback that also internal header files within a plugin would be public.
E.g. for the action plugin, `action.h` should be public but `action_impl.h` should not.

**Comment by Stifael** [comment]
ok.
Have you ever tried to run one of the examples without having it installed on the system?

**Comment by Stifael** [comment]
for instance: https://github.com/dronecore/DroneCore/blob/develop/example/offboard_velocity/offboard_velocity.cpp#L15 only works when it is installed on the system.

**Comment by julianoes** [comment]
Another way would be to install the plugin header files in a `plugins` subdirectory. That way the installed directory structure would be closer to the non-installed one.

The change would be to install it as:
```
dronecore/plugins/action/action.h
```
instead of:
```
dronecore/action.h
```

**Comment by julianoes** [comment]
@Stifael is this still an issue or can this get closed?

**Comment by Stifael** [comment]
no issue. can be closed.
