### ISSUE TITLE
Trace-coordinated mode

### ISSUE THREAD

**Issue by dangviethieu-hntv** [Dronecode/DronecodeSDK#451]
Hi all, can tell me whether dronecore support trace-coordinated mode, like DJI ?
https://gyazo.com/a724d2ba73a51775cc6c37ed23dc29b1

**Comment by julianoes** [comment]
@dangviethieu-hntv I don't think that's supported because it first would need to be supported by the PX4 Firmware.

**Comment by dangviethieu-hntv** [comment]
@julianoes Thanks you so much !!!
