### ISSUE TITLE
Unregister all mavlink message handlers

### ISSUE THREAD

**Issue by NiiAAip** [Dronecode/DronecodeSDK#464]
https://github.com/Dronecode/DronecodeSDK/blob/6e1d5e7e23eb6af38485843b48a67bda7b106756/core/system_impl.cpp#L81
I think that function may unresgister all mavlink message handlers of one plugin. Other plugins don't work when I unregister one of these plugins. Should we delete this code '_mavlink_handler_table.clear();'?

**Comment by julianoes** [comment]
Oops, I think you're right!
