### ISSUE TITLE
[Update Docs] Action::Result is moved to ActionResult

### ISSUE THREAD

**Issue by mzahana** [Dronecode/DronecodeSDK#484]
Just a little note here.

In the documents on [Actions](https://sdk.dronecode.org/en/guide/taking_off_landing.html), it mentions the use of `Action::Result`. The compile will fail as it seems that it is moved to `ActionResult`

**Comment by hamishwillee** [comment]
Thanks! Fixed in https://github.com/dronecore/sdk_docs/commit/ce61207bfcd564481c0d9601ed944fb54886bc57

I can't track changes as well as I'd like, so much appreciate you pointing them out.
