### ISSUE TITLE
How Can I fly without GPS at indoor ?

### ISSUE THREAD

**Issue by saucompeng** [Dronecode/DronecodeSDK#538]
I want to fly at indoor without GPS, code waiting at telemetry->health_all_ok() function. When I comment home_position_ok && global_position_ok && local_position_ok in function, it is not successfull ?

**Comment by hamishwillee** [comment]
Not supported: https://sdk.dronecode.org/en/getting_started/faq.html#does-the-sdk-support-indoor-use
