### ISSUE TITLE
Can't test the calibration successfully

### ISSUE THREAD

**Issue by JonasVautherin** [Dronecode/DronecodeSDK#594]
I have trouble getting the calibration to work. Running HITL on an H520, I either get a failure (`BUSY`) or one `IN_PROGRESS` event and nothing more.

@julianoes: is it right that the calibration ends when `SUCCESS` or an error result has been sent, and that it can send infinitely many `IN_PROGRESS` or `INSTRUCTION` events before that?

**Comment by julianoes** [comment]
Can you try not in HITL mode?

**Comment by JonasVautherin** [comment]
Yep, I'm setting up a mavlink router to test on a pixhawk

**Comment by JonasVautherin** [comment]
I managed to use the mavlink-router eventually. Seems like the calibration works fine now.
