### ISSUE TITLE
add_XXX_connection() could be better named

### ISSUE THREAD

**Issue by hamishwillee** [Dronecode/DronecodeSDK#61]
Using connection here means that any description of the API is riddled with the word connection - since we also have to connect to the device. It is probably worth using something like  `add_XXX_port()` to make it clear that this is just part of the whole "connect to devices" process.

**Comment by julianoes** [comment]
@JonasVautherin do you think that `add_XXX_port()` would be better?

**Comment by JonasVautherin** [comment]
But it actually adds the connection, right? `add_udp_connection()` means "listen for the next mavlink broadcast you find using UDP and actually setup the connection to it". `add_udp_port()` may sound like "start listening on a new port", wouldn't it?

**Comment by julianoes** [comment]
I mean actually it does start to listen and does not actually establish a connection to the drone as such.

**Comment by JonasVautherin** [comment]
Couldn't we split it into `start_XXX_discovery()`, that would return information about the discovered drones, and `connect_XXX(...)` which would take that information and actually start the connection?

**Comment by julianoes** [comment]
I guess but it's more complicated for an SDK user. `connect` is sort of the `auto System = dronecore.get_system()` call.

**Comment by JonasVautherin** [comment]
Right, I see.

**Comment by julianoes** [comment]
I vote we leave it as is.

**Comment by hamishwillee** [comment]
Sure. This does not seem to be causing any confusion.
