### ISSUE TITLE
Get mavlink messages through the SDK

### ISSUE THREAD

**Issue by douglaswsilva** [Dronecode/DronecodeSDK#721]
We'd like to be able to read mavlink messages in the Swift SDK, similar to what QGC has. For instance, we were having problems with starting mission and didn't know what the problem was until we look at the debug logs in our console to see this message: 
```
[12:57:31|Debug] MAVLink: critical: Maximum distance from home exceeded by 18.1 m (system_impl.cpp:292)
```

We'd like to get this message as part of telemetry or something else, so we could display it to user.

**Comment by douglaswsilva** [comment]
We can try to implement it ourselves, but want to have your guys input on what would be a good way to go about implementing it. @julianoes

**Comment by JonasVautherin** [comment]
@julianoes: Would it make sense to add that to `Telemetry`, or another plugin?

**Comment by julianoes** [comment]
Ok it's good that you're describing the actual problem which is that you need to know when and why things don't work. @bkueng is actually working on a proposal and implementation to address exactly this problem. This means we should get much more status information like this in the not so distant future :).

Now until then, we might want to just add the statustext messages to telemetry, it's just a `char[50]`, so nothing fancy.

**Comment by JonasVautherin** [comment]
The next step for adding the statustext to the telemetry is to make a PR on the [API definition](https://github.com/Dronecode/DronecodeSDK-Proto/blob/master/protos/telemetry/telemetry.proto) :-).

**Comment by douglaswsilva** [comment]
Done with: https://github.com/Dronecode/DronecodeSDK/pull/733

**Comment by douglaswsilva** [comment]
Done in: https://github.com/Dronecode/DronecodeSDK/pull/733
