### ISSUE TITLE
Modifying PX4 parameters using DronecodeSDK

### ISSUE THREAD

**Issue by eyewy** [Dronecode/DronecodeSDK#751]
Is there a way to modify the parameters listed at:
https://dev.px4.io/en/advanced/parameter_reference.html
using C++ SDK? As an example, in the takeoff_and_land.cpp example, is there a way to modify MIS_TAKEOFF_ALT parameter before arming and takeoff?

**Comment by hamishwillee** [comment]
Yes, use the [Param](https://sdk.dronecode.org/en/api_reference/classdronecode__sdk_1_1_param.html) plugin/class. It isn't fully documented, but has the same usage pattern as other plugins. There is also test code.
